# =========================================================
# Grafana | Datasource Provisioning (Auto-load)
# =========================================================
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://mindscan-prometheus:9090
    isDefault: true
    editable: true
