# sonar-project.properties
sonar.projectKey=mindscan
sonar.organization=inovexa
sonar.projectName=MindScan
sonar.projectVersion=1.0

# Código-fonte
sonar.sources=backend
sonar.language=py
sonar.sourceEncoding=UTF-8

# Testes e cobertura
sonar.tests=backend/tests
sonar.python.coverage.reportPaths=coverage.xml

# Ignorar arquivos
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/migrations/**,**/.venv/**
